import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import { useState } from 'react'
import Link from 'next/link'
import Typingmain from '@/components/Typingmain'
const port = process.env.PORT || 3000;

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  const [data, setdata] = useState(props.data.data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <Typingmain/>
        </div>
        <Image className={styles.img}
          src='/image1.avif'
          width={300}
          height={300}
          alt="Picture of the author"
          />
        <h2 className={styles.center}>Popular latest Blog By CodeHunter</h2>
        <div className={styles.titlecenter}>
        <ol>
        {data.map((e) => {
          let s = e.split('-');
          let p = "";
          for (let i = 0; i < s.length; i++) {
            p += (s[i] + ' ');
          }
          return <li key={e}><Link href={`/blogposts/${e}`}><h1 className={styles.lists}>{p}</h1></Link></li>;
        })}
      </ol>
      </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  // Fetch data from external API
  const res = await fetch(`http://localhost:3000/api`);
  const data = await res.json();
  // Pass data to the page via props
  return { props: { data } }
}
